// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg4-SPQaeBop2EMlpIKNo-so8V_GuYzzE',
    appId: '1:394331758141:web:586f5ccc7b592b0b675454',
    messagingSenderId: '394331758141',
    projectId: 'hostelites-4c563',
    authDomain: 'hostelites-4c563.firebaseapp.com',
    storageBucket: 'hostelites-4c563.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1Qowy1MywpxdvHjuKV2SFqBR-qTOL1g',
    appId: '1:394331758141:android:8b57ff58e5222f06675454',
    messagingSenderId: '394331758141',
    projectId: 'hostelites-4c563',
    storageBucket: 'hostelites-4c563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTRd8MshYZwm4-5iBYnUwg08svFVqFno',
    appId: '1:394331758141:ios:eaa1fb3f4b8f42d4675454',
    messagingSenderId: '394331758141',
    projectId: 'hostelites-4c563',
    storageBucket: 'hostelites-4c563.appspot.com',
    iosBundleId: 'com.example.hostelites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTRd8MshYZwm4-5iBYnUwg08svFVqFno',
    appId: '1:394331758141:ios:d0b16590e8754cfb675454',
    messagingSenderId: '394331758141',
    projectId: 'hostelites-4c563',
    storageBucket: 'hostelites-4c563.appspot.com',
    iosBundleId: 'com.example.hostelites.RunnerTests',
  );
}
